### PR TITLE
Milestome 2: feature/components

### PR DESCRIPTION
**Pull request by alvp01**
In this milestone I will create a calculator using react class components.

**Requirements:**
- Delete all the boilerplate from CRA (text, images, styles).
- Create a directory called components.
- Inside components, create a new Calculator.js file.
- Don't add any extra design.
- Develop just the UI of the calculator; the math logic to make it work will be added in the next project.
- Use class based components.
- Once the Calculator is ready, import it and use it in your main component (App.js).
- Test it in the browser; it should render without problems.

### CODE REVIEW

**Review by eliasecasta — CHANGES_REQUESTED** [review]
# Status:  Changes Required ♻️
_Check the comments under the review_
<hr>

Hello @alvp01, I am Elias, your reviewer for this PR

Well done so far with your project!

I really liked the personal style that you gave to your calculator, great job so far with it 👍 

I will mention to you a small summary of things that need to be changed in order to keep moving:

- [x] Please remove all the created files by create react app command, everything else looks awesome!

Please correct those issues and send another review request, good luck, and well done so far! 

Code review by Elias Castañeda

_(Feel free to leave any questions or comments in the PR thread if something is not 100% clear)_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/restricted?return_to=https%3A%2F%2Fmicroverse.zendesk.com%2Fhc%2Fen-us%2Farticles%2F1500004088561) you have a limited number of code reviews per project (you can check the exact number in your Dashboard). If you think that the code review was not fair, you can [request a second opinion using this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by alvp01** [comment]
> # Status: Changes Required 
> _Check the comments under the review_
> 
> Hello @alvp01, I am Elias, your reviewer for this PR
> 
> Well done so far with your project!
> 
> I really liked the personal style that you gave to your calculator, great job so far with it +1
> 
> I will mention to you a small summary of things that need to be changed in order to keep moving:
> 
> * [x]  Please remove all the created files by create react app command, everything else looks awesome!
> 
> Please correct those issues and send another review request, good luck, and well done so far!
> 
> Code review by Elias Castañeda
> 
> _(Feel free to leave any questions or comments in the PR thread if something is not 100% clear)_
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/restricted?return_to=https%3A%2F%2Fmicroverse.zendesk.com%2Fhc%2Fen-us%2Farticles%2F1500004088561) you have a limited number of code reviews per project (you can check the exact number in your Dashboard). If you think that the code review was not fair, you can [request a second opinion using this form](https://airtable.com/shrQAqnBwek5a0O0s).

Done, thanks.

**Review by BrianSammit — APPROVED** [review]
# STATUS: APROVED :green_circle: :clap: 

Hello @alvp01, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

well-1

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by alvp01** [comment]
> # STATUS: APROVED  
> Hello @alvp01, Your project is complete! There is nothing else to say other than... Great job clap Congratulations! tada
> 
> Now you can merge this branch and move on 1st_place_medal HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES crossed_fingers four_leaf_clover
> 
> well-1
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thank you for your time and work!

**Pull request merged**
